- deployments/azure_bicep/modules/apps-nutsnode.bicep
- Pins Nuts node to specific version (v6.0.0-beta.2). A new master image didn't cause a pull, so pinning for now.
- Switches fs crypto storage for Azure Key Vault
- Removes FHIR service dependency from Nuts node (Nuts node does not use it)
> Enable Azure KeyVault in Bicep deployment

- orchestrator/applaunch/clients/factory.go
- orchestrator/applaunch/demo/service.go
- orchestrator/applaunch/smartonfhir/service.go
- orchestrator/careplancontributor/config.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/service.go
- orchestrator/cmd/config.go
- orchestrator/cmd/server.go
- orchestrator/lib/coolfhir/client.go
- orchestrator/lib/coolfhir/proxy.go
That forward calls to CarePlanService and local EHR FHIR API.
For EHR: `/contrib/ehr/fhir`
For CPS: `/contrib/cps/fhir`
Proxy code did already exist for the CarePlanService, moved it to `lib` to be reusable, made authentication dependent on app launch.
Also introduces an endpoint for the frontend to retrieve the session data (launch context): `/contrib/context`.
> CarePlanContributor: have proxy endpoints

- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/handle_updatetask_test.go
- orchestrator/careplanservice/integration_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/lib/auth/auth.go
- orchestrator/lib/auth/test.go
- orchestrator/lib/coolfhir/util.go
When updating a task in CarePlanService there are only certain status transitions that are valid, otherwise return error.
Adds unit tests and updates integration test
To follow: Fetch owner and requester of task to validate that they are allowed to make the status change
> INT-238: Implement state transition validation for Task update in CPS

- orchestrator/careplancontributor/config.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/config.go
- orchestrator/careplanservice/config_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/cmd/server.go
- orchestrator/lib/coolfhir/azure.go
- orchestrator/lib/coolfhir/azure_test.go
Adds a FHIR proxy endpoint for method calls from one CPC instance to another.
Still to do: Auth based on provided CareTeam, E2E integ test
> INT-241: Add FHIR proxy for CPC to CPC calls

- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/integration_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/cmd/config.go
- orchestrator/cmd/profile/nuts/auth.go
- orchestrator/cmd/profile/nuts/auth_test.go
- orchestrator/cmd/profile/nuts/config.go
- orchestrator/cmd/profile/nuts/csd.go
- orchestrator/cmd/profile/nuts/csd_test.go
- orchestrator/cmd/profile/nuts/httpclient.go
- orchestrator/cmd/profile/nuts/profile.go
- orchestrator/cmd/profile/nuts/profile_test.go
- orchestrator/cmd/profile/profile.go
- orchestrator/cmd/profile/test.go
- orchestrator/cmd/server.go
- orchestrator/lib/auth/auth.go
- orchestrator/lib/auth/test.go
This PR introduces a `Profile` concept that allows you to "configure" (although it's still in code) how to authenticate and find endpoints of other SCP nodes. The only implementation is "Dutch-Nuts";
- Nuts provides authentication through its OAuth2 access tokens
- Nuts provides CSD endpoint lookup through its Discovery Service
- Dutch provides a mapping of URA naming system to fields in the URACredential, required to find organizations in the Nuts Discovery Service given their URACredential.
This also moves all authentication concerns from tests in the (CPC and CPS) service layer to the profile implementation.
> Abstract Nuts support through Profile abstraction refactor

- .github/workflows/orchestrator.yaml
Was there previously, got cleaned up by accident.
> e2e tests: use image tag provided by CI

- hospital_simulator/next.config.js
- hospital_simulator/package-lock.json
- hospital_simulator/package.json
- viewer_simulator/next.config.js
Attempt to fix:
```
`x-forwarded-host` header with value `(etc).westeurope.azurecontainerapps.io:443` does not match `origin` header with value `(etc).com` from a f...
```
Refer to https://github.com/vercel/next.js/issues/58295
> NextJS: allow nextjs' allowedOrigins to be configured

- orchestrator/Dockerfile
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/service.go
- orchestrator/go.mod
- orchestrator/lib/coolfhir/proxy_test.go
We need to stay cool.
Had to change URL routing wildcard paths, since it apparently changed in 1.23.
> Upgrade to Go 1.23

- e2e-tests/config/nuts/discovery/homemonitoring.json
- e2e-tests/nuts.go
- orchestrator/careplanservice/subscriptions/channels.go
With Service Discovery definition as determined by the use case.
Also requires upgrading Nuts node to rc.10
> Align FHIR notification URL Discovery Service parameter 

- e2e-tests/main_test.go
- orchestrator/careplanservice/subscriptions/manager.go
Check the Owner and Requester identifier directly rather than using the existing `IsLogicalReference` check which requires a type be set
> Support Type for Task Owner and Requester being optional

- deployments/dev/start.sh
- orchestrator/careplancontributor/handle_taskfiller.go
- orchestrator/careplancontributor/integration_test.go
- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_createtask_test.go
- orchestrator/careplanservice/handle_gettask.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/integration_test.go
- orchestrator/lib/coolfhir/util.go
Dev testing was broken as we could create tasks but would not see the questionnaire, this was due to the task filler not being notified due to an incorrect endpoint and validation logic that would reject it.
Endpoint has been updated to the correct one, and new validation logic for SCP subtasks has been implemented
> Fix questionnaire subtask filling

- deployments/dev/start.sh
- orchestrator/careplanservice/handle_getcareplan.go
- orchestrator/careplanservice/handle_gettask_test.go
We were searching for a CareTeam in an empty bundle, causing failures
> [INT-398] If bundle in CarePlan search is empty, return early

- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/user/session.go
- orchestrator/user/session_test.go
Add endpoint for logout which destroys the current session and redirects the user back to the base frontend URL
Still TODO is to redirect to a real logout page, which has not been created yet
> [INT-370] Create logout endpoint

- e2e-tests/main_test.go
- e2e-tests/orca.go
- orchestrator/careplanservice/config.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
Add a flag that allows unmanaged FHIR operations, default behaviour is that they are not allowed
> [INT-405] Disallow unmanaged FHIR operations in CPS

- orchestrator/careplanservice/handle_getcareplan.go
- orchestrator/careplanservice/handle_getcareteam.go
- orchestrator/careplanservice/handle_gettask.go
Refactor query parameter loops to handle multiple values per key in the `handleSearchTask`, `handleSearchCareTeam`, and `handleSearchCarePlan` functions. This ensures that all values for a given query parameter key are included, improving the handling of multi-value parameters.
> Update query parameter handling in care services

- frontend/lib/fhirUtils.ts
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/handle_taskfiller.go
- orchestrator/careplancontributor/handle_taskfiller_test.go
Fixes:
- Always use primary Task's reason to resolve the service (telemonitoring), as the subtask might not have it
- Zorgplatform's Task must refer to the ServiceRequest by ID (fixes error: `failed to process new primary Task: task.Focus or task.Focus.Reference is nil`)
- Zorgplatform's ServiceRequest should not have a logical identifier denoting the condition code
> Fix integration of Zorgplatform

- orchestrator/careplancontributor/applaunch/zorgplatform/handle_create_hcp_rst.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_integration_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
- orchestrator/careplanservice/careteamservice/careteam.go
- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/handle_updatetask_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/lib/coolfhir/bundle.go
Otherwise, we're going to have to hardcode it. Zorgplatform app launch already has the URA, so we can just read it from CSD.
Improve unit test coverage in the meantime (and fix a bug)
> Zorgplatform: read Task performer name from CSD

- orchestrator/README.md
- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_createtask_test.go
- orchestrator/careplanservice/service.go
- orchestrator/cmd/config.go
- orchestrator/cmd/config_test.go
- orchestrator/main.go
Note: ongoing tests, more might be added.
We found issues with the processing of `POST Task` transaction result processing on Azure FHIR.
Changes:
- Log transaction request and result bundle
- Introduce ORCA_LOGLEVEL config parameter (default: info)
- Support Azure FHIR's absolute URL (HAPI provides relative URLs) in bundle response `Location` header, which is used to select the right resource to return from a TX bundle
TODO:
> INT-419: Microsoft Azure FHIR compatiblity

- hospital_simulator/app/(DashboardLayout)/components/service-requests/service-request-overview.tsx
- hospital_simulator/app/(DashboardLayout)/components/service-requests/service-request-table.tsx
- orchestrator/careplancontributor/applaunch/demo/service.go
- orchestrator/careplancontributor/applaunch/demo/service_test.go
- orchestrator/user/session.go
Also showing the `ServiceRequest.reasonReference` in the EHR mock.
I've create a [separate issue](https://linear.app/zorg-bij-jou/issue/INT-446/orca-or-support-multiple-launches-in-one-browser) on how to support multiple launches in one browser.
> INT-436: Destroying the previous session on demo launch (if found). 

- orchestrator/cmd/profile/nuts/csd.go
- orchestrator/cmd/profile/nuts/csd_test.go
- orchestrator/cmd/profile/nuts/profile.go
- orchestrator/cmd/profile/nuts/profile_test.go
Nuts profile only worked with NutsUraCredential, while UziServerCertificateCredential contains an encoded URA.
> Support UziServerCertificateCredential

- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/integration_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/lib/coolfhir/bundle.go
- orchestrator/lib/coolfhir/bundle_test.go
- orchestrator/lib/test/hapi.go
It failed because we need the resource being updated for sending notifications. But, sometimes Azure FHIR doesn't populate `Bundle.entry.response.location`. This caused nil derefs in multiple spots.
Made a more rigorous (and better tested) function, simplified the getting the right bundle entry to resepond with in the our FHIR operation handlers.
> Ignore nil response.Location for unmanaged FHIR operations

- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
Mapping the `ServiceRequest` to the Zorgplatform `workflow-id`. Zorgplatform does not work with a `ServiceRequest`, but a `Task` for orders. They serve the same purpose, so they are mapped. This allows for querying the Zorgplatform data later on.
> Persist Zorgplatform workflow-id

- orchestrator/careplanservice/handle_getpatient_test.go
- orchestrator/careplanservice/integration_test.go
- orchestrator/careplanservice/util.go
- orchestrator/lib/coolfhir/error.go
To prevent accidentally omitting fields.
The problem was we created a new Bundle, now we simply take a copy instead.
> CPS: return original bundle stripped from unauthorized resources

- orchestrator/careplancontributor/applaunch/demo/service.go
- orchestrator/careplancontributor/applaunch/smartonfhir/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_create_access_token.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_validation.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_validation_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/handle_taskfiller.go
- orchestrator/careplancontributor/handle_taskfiller_test.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/taskengine/questionnaire.go
- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_getcareplan.go
- orchestrator/careplanservice/handle_getcareteam.go
- orchestrator/careplanservice/handle_getcondition.go
- orchestrator/careplanservice/handle_getpatient.go
- orchestrator/careplanservice/handle_gettask.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/subscriptions/manager.go
- orchestrator/careplanservice/util.go
- orchestrator/cmd/profile/nuts/auth.go
- orchestrator/lib/az/azkeyvault/test.go
- orchestrator/lib/coolfhir/util.go
Then we can start including fields such as authorized user and trace/span IDs in all log messages.
> Pass context to loggers to prepare for contextual logging

- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/go.mod
- orchestrator/go.sum
- orchestrator/lib/coolfhir/azure.go
- orchestrator/lib/coolfhir/error.go
- orchestrator/lib/coolfhir/proxy.go
- orchestrator/lib/coolfhir/proxy_test.go
On Azure FHIR, the following query returns HTTP 400 Bad Request, without response body:
```
/orca/cpc/cps/fhir/ServiceRequest?identifier=2.16.528.1.1007.3.3.21514.ehr.orders%7C99534756439a
```
The same goes for `ServiceRequest?_id=2`
Fix:
I couldn't find out why it failed, but it was something in the usage of `httputil.ReverseProxy`. I rewrote our FHIR proxy to use `fhirclient.Client`, which worked. This should also improve the consistency of HTTP responses (headers, marshalling format). This thus applies to the actual issue (CPS proxying to Azure FHIR), but is now also used by the CPC->CPS proxy (which uses the same). But tests still work, so should be OK.
Also improved proxy logging (it now logs a proxy name, since some requests are routed through 2 proxies, making logging very hard to …
> Troubleshoot Bad Request response without response body

- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/lib/coolfhir/proxy.go
- orchestrator/lib/coolfhir/proxy_test.go
- No caching for browser-facing FHIR APIs
- Private caching for system-facing FHIR APIs
> INT-481: Cache-Control for FHIR APIs

- orchestrator/careplancontributor/config.go
- orchestrator/careplancontributor/config_test.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/taskengine/workflow.go
- orchestrator/careplancontributor/taskengine/workflow_test.go
- orchestrator/lib/coolfhir/util.go
As alternative to Questionnaire/HealthcareService FHIR resources from FHIR API. Useful if a vendor doesn't want to load questionnaires/healthcareservices in their FHIR instance.
It filters the HealthcareService and Questionnaire v.s. the ServiceRequest code and Condition code in-memory, instead of searching them in the FHIR API.
The downside is, that on boot the (external) source of the FHIR bundles MUST be up and running, otherwise ORCA will fail to start.
> INT-464: Implement in-memory workflow provider 

- orchestrator/lib/coolfhir/proxy.go
- orchestrator/lib/coolfhir/proxy_test.go
A new `err` var was used that shadowed the shared `err` var, which caused the proxy to return status code `0` (which causes issues downstream).
> INT-511: FHIR proxy ignores upstream errors on POST-search

- frontend/app/enrollment/layout.tsx
The horizontal ruler exceeded the viewport width due to a width calculation that added extra margin, for reasons to me unknown. `div` elements span the full parent element width by default, so there's no need for setting width (at least, to my limited CSS knowledge).
> INT-524: Fix superfluous horizontal scroll bar

- orchestrator/README.md
- orchestrator/careplancontributor/applaunch/demo/service.go
- orchestrator/careplancontributor/applaunch/demo/service_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
- orchestrator/careplancontributor/config.go
- orchestrator/careplancontributor/service.go
- orchestrator/cmd/server.go
Before, there was a redirect to the frontend if the user requested an unknown URL. But, this caused weird redirects, so it was removed. But now, the redirect after app launch is broken since they redirected to an incorrect URL.
Previously, it redirected to `/orca/cpc` (if `/orca` were the configured base URL), now it correctly redirects to the `/frontend/enrollment/new` URL.
> INT-525: Fix redirect to frontend after applaunch

- orchestrator/careplancontributor/handle_taskfiller.go
Use "Update" for Questionnaire creation in transaction.
Replaced `Create` with `Update` for the Questionnaire in the FHIR transaction, aligning with the correct resource reference format. Adjusted the `questionnaireRef` to use "Questionnaire/" prefix for consistency with FHIR standards. Removed obsolete comment and unnecessary entry modifications.
> INT-496: ORCA CPC ZbJ | BUG: The questionnaire is created multiple times in the FHIR store, causing the task submission to fail.

- orchestrator/careplanservice/integration_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/lib/test/fhirclient.go
- orchestrator/lib/to/util.go
The SearchParameter existed, but wasn't working. It also wasn't in the CapabilityStatement, which indicates it needs to be re-indexed:
> The new search parameter will appear in the capability statement of the FHIR server after you POST the search parameter to the database and reindex your database. Viewing the SearchParameter in the capability statement is the only way tell if a search parameter is supported in your FHIR server. If you can find the search parameter, but cannot see it in the capability statement, you still need to index the search parameter. You can POST multiple search parameters before triggering a reindex operation.
(https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/how-to-do-custom-search)
I also made creating the SearchParameters less fiddly, …
> INT-521: Re-index SearchParameter on Azure FHIR if it exists, but isn't in the CapabilityStatement

- orchestrator/careplancontributor/service.go
- orchestrator/lib/coolfhir/util.go
- orchestrator/lib/coolfhir/util_test.go
- viewer_simulator/app/(DashboardLayout)/components/bgz/actions.ts
`authorizeScpMember()` fails if the CPS runs on a non-root base URL (e.g. `/orca`), due to the way the CarePlan ID is parsed from the X-SCP-Context URL.
> INT-487: Support non-root base URL in EHR proxy

- hospital_simulator/utils/config.ts
- orchestrator/careplancontributor/applaunch/demo/service.go
- orchestrator/careplancontributor/applaunch/demo/service_test.go
- orchestrator/lib/coolfhir/util.go
- orchestrator/lib/coolfhir/util_test.go
Instead of double-encoding the system in the token
> INT-473: Parse passed existing task ID for demo launch

- deployments/dev/hospital/docker-compose.yaml
- frontend/lib/fhirUtils.ts
- orchestrator/careplancontributor/applaunch/demo/service.go
- orchestrator/careplancontributor/applaunch/demo/service_test.go
- orchestrator/careplancontributor/applaunch/smartonfhir/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
- orchestrator/cmd/server.go
- orchestrator/lib/must/util.go
Ran into two issues that @rolandgroen also brought up so decided to fix them as it is simple.
One is that enrollment went to a 404 due to the URL having "/new/new" at the end, the other is some leftover change from the ifNotExists revert that was not removed, this has been commented as it was causing enrollment to fail. This issue was picked up on the main branch
> Fixes duplicate URL value and task enrollment failure

- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
- orchestrator/careplancontributor/handle_taskfiller.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/subscriptions/channels.go
- orchestrator/cmd/profile/nuts/profile.go
- orchestrator/cmd/profile/nuts/profile_test.go
- orchestrator/cmd/profile/profile.go
- orchestrator/cmd/profile/test.go
- orchestrator/lib/coolfhir/util.go
The FHIR Encounter resource is not always present when launched from ChipSoft HiX, so we can't rely on it. This PR fixes the following:
- Removes resolution of Encounter resource
- Removes identification of Patient resource through `Encounter.subject.reference`; Zorgplatform uses search narrowing, so the only Patient resource returned will be the one specified in the Zorgplatform API auth token (which' BSN was provided in the HiX launch token).
- Removes identification of the local care organization (requesting the order) through the Encounter.
- Changed this to be loaded from the local wallet
- We want FHIR `Organization.name` to be set, so I reworked `Profile.Identities()` to return `fhir.Organization` instead of only the organization's identifiers.
Note: this functionality will be …
> INT-544: Remove use of Encounter on Zorgplatform launch

- orchestrator/careplancontributor/applaunch/smartonfhir/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_validation.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/ehr/kafka_client.go
- orchestrator/careplancontributor/ehr/notifier.go
- orchestrator/careplancontributor/handle_taskfiller.go
- orchestrator/careplancontributor/handle_taskfiller_test.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_getcondition.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/subscriptions/manager.go
- orchestrator/careplanservice/util.go
- orchestrator/cmd/profile/nuts/auth.go
- orchestrator/cmd/profile/nuts/auth_test.go
- orchestrator/cmd/profile/nuts/profile.go
- orchestrator/globals/globals.go
- orchestrator/lib/auth/auth.go
- orchestrator/lib/coolfhir/util.go
- orchestrator/main.go
Set during authentication, it causes the user to be added as field to log entries. This means we log the URA of the authenticated organization as `principal` field in `<system>|<value>` format.
For example:
```json
{"level":"info","principal":"http://fhir.nl/fhir/NamingSystem/ura|1","time":"2025-01-26T08:42:13+01:00","message":"test"}
```
> INT-560: Add authentication user to every log entry

- orchestrator/careplanservice/subscriptions/manager.go
- orchestrator/careplanservice/subscriptions/manager_test.go
Fixes the following log line that appears now and then in our logging:
```
CarePlanContributor/Notify failed: Notification focus type is nil
```
> Fix notification focus type being nil

- frontend/lib/fhirUtils.ts
- hospital_simulator/app/(DashboardLayout)/components/service-requests/create-service-request-dialog.tsx
Re-enable IfNoneExists headers to ensure enrollment is persisted for the same task per ServiceRequest, prevents duplicate ServiceRequests and Tasks from being created
> INT-559 | Prevent duplicate Task enrollment

- frontend/app/layout.tsx
Was only able to reproduce this on a windows machine. As soon as I removed the w-screen and h-screen from the /app/layout.tsx the problem was solved. The w-screen was like 12px wider than the full width for some reason..
> INT-524: Fixed horizontal scrollbar. 

- orchestrator/careplanservice/handle_createtask.go
While looking at the code to see how a `CarePlan` is being created I noticed a dangling err check. I'm pretty sure it's a left-over of code that has been refactored.
> Remove dangling err check

- orchestrator/careplanservice/handle_createtask.go
While looking at the code to see how a `CarePlan` is being created I noticed that the result handler of `handleCreateTask(..)` populates an array of notifications but incorrectly returns a hardcoded slice instead which results in a missing notification for the `CareTeam` in a task.
It seems like this should work similarly to `handleUpdateTask(..)` (which does return the `notifications` variable).
> Return notifications properly in create task handler

- viewer_simulator/app/(DashboardLayout)/components/bgz/bgz-overview.tsx
- viewer_simulator/app/(DashboardLayout)/components/onboarding/accepted-task-overview.tsx
The notification mechanism is not working correctly in dev and test, re-enable fetching Task and CarePlan if there are no records so we can still do tests and demos while figuring out the notifications
> Temporarily re-implement viewer searching for task and careplan

- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_createtask_test.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/lib/coolfhir/bundle.go
- orchestrator/lib/coolfhir/bundle_test.go
Azure FHIR only returns 200 OK when a conditional create matched an existing resource. Our normalization code didn't know what to do in this case.
The normalization code already reads the resource in case the FHIR API doesn't return it, looking at things like `location` properties and upserts. But, we didn't handle `ifNoneExist` yet. In this case, we need to do a search.
Also improved the existing "search" for upserts (it used a `Read()` before, so the returned result was incorrect).
Also added passing of context to the FHIR client, so tracing headers and time-outs (which we both don't have yet) will be honored.
> INT-570: Handle empty matched conditional create resource result on Azure FHIR

- frontend/app/enrollment/new/components/enrollment-details.tsx
- frontend/app/enrollment/task/[taskId]/page.tsx
These values aren't display values of codes, but dictated by the EHR (patient name) or as the care organization is registered (from the Verifiable Credential/CSD). So we shouldn't alter the casing.
> Frontend: don't upper-case patient name and care organization

- orchestrator/careplancontributor/mock/fhirclient_mock.go
- orchestrator/careplanservice/handle_createtask_test.go
- orchestrator/careplanservice/integration_test.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/service_test.go
- orchestrator/go.mod
- orchestrator/go.sum
- orchestrator/lib/coolfhir/bundle.go
- orchestrator/lib/coolfhir/bundle_test.go
- orchestrator/lib/coolfhir/pipeline/pipeline.go
- orchestrator/lib/coolfhir/proxy.go
- orchestrator/lib/coolfhir/proxy_test.go
- orchestrator/lib/test/fhirclient.go
Useful for cleaning up test data, since testing sometimes involves creating a new patient in the downstream EHR.
This allows parties to delete the related resources (e.g. Task, CarePlan, ServiceRequest and Patient) and re-send the order.
A lot of the changes are associated with FHIR API returning no response body in case the delete succeeds (204 No Content)
> INT-569: Support DELETE when unmanaged operations are allowed

- orchestrator/careplancontributor/service.go
- orchestrator/cmd/profile/nuts/profile.go
- orchestrator/cmd/profile/nuts/profile_test.go
The endpoint for the EHR (e.g. Viewer Demo app) to exchange with the CPS only worked with the local CPS. But, in case of Zorg bij jou, the CPS is remote (e.g. Faux Care, SAZ or ZPF).
Currently (broken), it always requests an access token at the local Nuts node to talk with the (assumed local) CPS, but this is wrong; it should look up the authorization server using the CapabilityStatement of the CPS.
This was broken by the earlier INT-568 change.
In the future, this should be optimized by the endpoint knowing whether it's the local CPS (then it can dispatch internally and doesn't need to go through the Nuts access token flow) or a remote one.
> INT-568: Fix proxy to CPS to work with exteral CPS' too (used by Viewer)

- orchestrator/careplancontributor/ehr/servicebus_client.go
This ensures the demo client sends the message to the viewer regardless of any downstream errors with the servicebus implementation
> Send ServiceBus message to demo client first

- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/webhook/eventhandler.go
- orchestrator/careplancontributor/webhook/eventhandler_test.go
- orchestrator/cmd/profile/nuts/csd.go
Basic webhook handler implementation. Sends a POST request containing the full resource encoded in JSON. Expects a HTTP 200 to succeed. Also tested manually.
> INT-596 | Implement webhook handler

- orchestrator/careplancontributor/config.go
- orchestrator/careplancontributor/config_test.go
- orchestrator/careplancontributor/integration_test.go
- orchestrator/careplancontributor/service.go
CPS is not required in CPC as we add support for multiple CPS's, if the CPS URL is not set then the proxy method will fail
> INT-386 | Disable requirement for CPS URL in CPC

- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_createtask_test.go
According to the [SCP specification](https://santeonnl.github.io/shared-care-planning/overview.html#careplan) the author should be set for a CarePlan. However, whenever a new CarePlan is created (based on a Task), it doesn't set the author.
> Set careplan author on creation

- frontend/.env.local.example
- frontend/app/actions.ts
- frontend/app/error.tsx
This error page contains a retry button and reports the `digest` and UTC timestamp of the error. The page instructs the user to send this information to support if the issue persists. The digest can be used to correlate to the error in the logs.
``` GET /enrollment/new 200 in 116ms
⨯ Error: Not implemented
at ConfirmDataPreEnrollment (app/enrollment/new/page.tsx:8:8)
6 | export default function ConfirmDataPreEnrollment() {
7 |
>  8 |   throw new Error('Not implemented')
|        ^
9 |
10 |   return (
11 |     <Card className="border-0 shadow-none px-0"> {
digest: '4196643865'
```
Added the `SUPPORT_CONTACT_LINK` env var to the frontend. When this is set, the "Neem contact op" subtext appears at the bottom, the the value is set as the anchor href. This can be a website, but also a …
> INT-573: Added a styled error page for uncaught exceptions. 

- hospital_simulator/app/(DashboardLayout)/components/service-requests/create-service-request-dialog.tsx
The BSN is defined as a 9 digit number. Using something different breaks stuff on the other side of the integration.
Fix: Limit patient BSN to 9 characters in service request. Updated the logic for generating patient BSN to ensure it is a 9-character string.
> INT-626: Hospital Simulator | BUG, mock BSN is not 9 digits

- hospital_simulator/app/(DashboardLayout)/components/service-requests/create-service-request-dialog.tsx
Add BSN generation with 11-proof validation
Implemented a utility function to generate Dutch citizen service numbers (BSN) that comply with the 11-proof validation logic. Replaced the previous placeholder BSN generation with the new validated approach to ensure number correctness.
> INT-629 - Hospital Simulator | Make the generated BSN 11proef enabled.

- orchestrator/go.mod
- orchestrator/go.sum
The updated go-nuts-client retries the HTTP request with a fresh access token, acquired from the Nuts node with `Cache-Control: no-cache`.
Also see https://github.com/nuts-foundation/go-nuts-client/pull/3
> INT-646: Retry unauthorized requests with a fresh access token

- viewer_simulator/app/(DashboardLayout)/components/bgz/bgz-overview.tsx
- viewer_simulator/app/(DashboardLayout)/components/onboarding/accepted-task-overview.tsx
- viewer_simulator/app/(DashboardLayout)/components/onboarding/create-task-observation.tsx
- viewer_simulator/app/(DashboardLayout)/components/onboarding/enrolled-task-table.tsx
- viewer_simulator/app/api/delivery/storage.ts
- viewer_simulator/app/api/fhir/[...fhirPath]/route.tsx
- viewer_simulator/eslint.config.mjs
- viewer_simulator/package-lock.json
- viewer_simulator/package.json
- viewer_simulator/utils/theme/DefaultColors.tsx
This PR adds the following:
1. The order Tasks that come from the hospitals now have a "pencil" icon in the "Onboarding Tasks" table.
2. When clicking this pencil, a popup is shown that allows for creation of a FHIR `Observation`
3. Rewrote the FHIR endpoint, that used to proxy to become a light-weight in-memory FHIR server. This to keep the configuration simple, and to not re-introduce a second HAPI server like we used to have.
4. The Observation is stored in the new light-weight FHIR server. The Observation can be queried here as well.
5. Also added a "fetch resources when there are no notifications in-memory" logic when the viewer is started from the dev server (`process.env.NODE_ENV === 'development'`). As the dev server does many hot reloads, the in-memory data is often cleared. This …
> INT-642 > INT-655: Create Observations from the MSC viewer

- deployments/dev/clinic/docker-compose.yaml
- orchestrator/careplancontributor/ehr/notification_bundle.go
- orchestrator/careplancontributor/ehr/notification_bundle_test.go
The enrolment bundle builder still worked under the assumption that CarePlan referenced CareTeam, and thus failed.
Also configured required messaging config.
> INT-630: Fix enrolment bundle building after making CareTeam contained within CarePlan

- viewer_simulator/app/(DashboardLayout)/components/onboarding/create-task-observation.tsx
This resulted in default routing to nuts instead of itself - causing a 404.
> INT-665: The creation of the Observation didn't keep the basePath in mind

- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/util.go
- orchestrator/lib/coolfhir/contained.go
> INT-630: Ignore old CarePlans with non-contained CareTeam

- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/integration_test.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplanservice/service.go
- orchestrator/lib/coolfhir/pipeline/rewriting.go
- orchestrator/lib/coolfhir/pipeline/rewriting_test.go
- orchestrator/lib/coolfhir/proxy.go
- orchestrator/lib/coolfhir/proxy_test.go
Helps with determining X-SCP-Context, if a proxy reports where it got the resource from. Only do for GET requests for now, only for top-level resources (nested resources not supported).
> INT-667: Have FHIR proxy set meta.source when querying remote FHIR APIs

- viewer_simulator/app/(DashboardLayout)/components/bgz/bgz-overview.tsx
- viewer_simulator/app/(DashboardLayout)/components/onboarding/accepted-task-overview.tsx
- Accepted Task overview is sourced primarily from received notifications and _may_ query FHIR_BASE_URL when running in dev mode
- The same applies to BgZ view, and it then uses the FHIR_AGGREGATE_URL to query the BgZ data
I'm removing the check, as I'll be removing the `FHIR_BASE_URL` from the configuration on test/acceptance (since it's not used).
> Viewer: ignore FHIR_BASE_URL for showing accepted Tasks or BgZ

- frontend/app/enrollment/components/questionnaire-renderer.tsx
- frontend/app/enrollment/components/sse-connection-status.tsx
- frontend/app/enrollment/task/[taskId]/page.tsx
- frontend/components/ui/hover-card.tsx
- frontend/lib/store/task-progress-store.ts
- frontend/package.json
- frontend/pnpm-lock.yaml
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- orchestrator/careplancontributor/sse/service.go
- orchestrator/careplancontributor/sse/service_test.go
- orchestrator/careplancontributor/testdata/task-3.json
The frontend can now subscribe to changes of a specific Task (with a valid session). Changes to that Task (or subtasks related to) are pushed to the browser. This is done via a generic "SSE" service. This service is injected into the CPC. It can be re-used for other topics as well. Currently only used for Task topics.
Removed the short-term polling solution, and the existing polling solution after a QuestionnaireResponse is created, and the application awaits the other party to process it.
The `EventSource` will automatically reconnect when the connection is lost. The bottom-right of the screen contains a "connected"-indicator of the SSE stream with the Go backend:
And on hover:
> INT-691: Added Server-Sent Events (SSE) to the CPC. 

- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/sse/service.go
**Why**
The `Task.meta.source` is used to determine the `X-Scp-Context` header
**What**
This allows the viewer to `/aggregate` all resources right after a `Task` update is pushed
Also changed the log level on a full publish channel, forgot to change this PR feedback  in the INT-691 PR
> INT-698: Set `Task.meta.source` on SSE push

- orchestrator/careplancontributor/handle_taskfiller.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplanservice/subscriptions/channels.go
- orchestrator/careplanservice/subscriptions/channels_test.go
- orchestrator/messaging/http.go
On the local dev server, the MSC viewer doesn't receive updates on the accepted Task anymore. The Task isn't pushed to the viewer, and is never listed any more.
> INT-701: Fix the Task accepted notification

- frontend/app/enrollment/components/questionnaire-renderer.tsx
Was used before when there were multiple Questionnaires. Now simply goes to the Task status page, so it'll be at the top after a new Task is received. 
If needed, this logic can be performed on Task updates, which is cleaner anyway.
> INT-700: Remove scrollToTop logic

- deployments/dev/start.sh
This prevents the start.sh script from failing if it can't remove tunnel files that don't exist
> Fix: start.sh failing if tunnel file does not exist

- orchestrator/careplanservice/handle_getcondition_test.go
- orchestrator/careplanservice/handle_getpatient_test.go
- orchestrator/careplanservice/handle_getquestionnaireresponse_test.go
- orchestrator/careplanservice/handle_getservicerequest_test.go
- orchestrator/careplanservice/handle_updatecondition_test.go
- orchestrator/careplanservice/handle_updatepatient_test.go
- orchestrator/careplanservice/handle_updatequestionnaireresponse_test.go
- orchestrator/careplanservice/handle_updateservicerequest_test.go
- orchestrator/careplanservice/integration_audit_test.go
- orchestrator/careplanservice/util.go
After some experimentation between HAPI FHIR and Azure FHIR I have determined that AuditEvent may not be a suitable mechanism for verifying creator-based auth.
For the mean time, we will keep creating audit events but they will not be used for authentication
> FIX | Disable audit based authorisation

- viewer_simulator/app/api/bgz/careplans/route.ts
Due to a bug in the way we handle search and amount of records returned in ORCA we are not returning CarePlans even when we should be, this solves one end of the problem for now while we work on a more robust solution on ORCA
> FIX | Add count to CarePlan search for BGZ viewer

- hospital_simulator/app/(DashboardLayout)/components/service-requests/create-service-request-dialog.tsx
Some downstream systems might be sending actual messages to these phone numbers, so use a fixed, non-existing one.
> Use a fixed phone number for new patients, to prevent accidentally sending messages to actual phones

- orchestrator/careplanservice/handle_getcondition.go
- orchestrator/careplanservice/handle_getcondition_test.go
- orchestrator/careplanservice/handle_getquestionnaire.go
- orchestrator/careplanservice/handle_getquestionnaire_test.go
- orchestrator/careplanservice/handle_getquestionnaireresponse.go
- orchestrator/careplanservice/handle_getquestionnaireresponse_test.go
- orchestrator/careplanservice/integration_audit_test.go
- orchestrator/careplanservice/service.go
- viewer_simulator/app/api/bgz/careplans/route.ts
The BGZ viewer does queries on all our data types using Search, previously this was handled by the proxy but this change implements Search for each type explicitly
> FIX | Implement missing search APIs

- e2e-tests/go.mod
- e2e-tests/go.sum
- e2e-tests/main_test.go
- frontend/lib/fhirUtils.ts
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/service_test.go
- viewer_simulator/app/api/bgz/careplans/route.ts
We introduced `/cpc/external/fhir`, a new proxy endpoint to which all other outbound FHIR endpoints should migrate. This PR removes the `/cpc/cps/fhir` endpoint, which is used to either call the local CPS (ORCA Frontend, to create Tasks) or the Viewer (to fetch CarePlans).
This removes the `X-Cps-Url` header on the old endpoint, in favor of the new `X-Scp-Fhir-Url` header on the new endpoint. This header can be used to indicate CPC or CPS FHIR APIs, not just CPS.
It can also still be used by the ORCA Frontend to call the local CPS API (like the old endpoint supported), by specifying `local-cps`.
> Remove CPS proxy endpoint in favor of generic SCP proxy endpoint

- orchestrator/careplanservice/handle_createtask.go
`Task.requester` is enriched with the care organization name, so we should use that one to make sure displayName is set.
> CPS: Use Task.Requester as CareTeam member, so displayName is set

- orchestrator/careplancontributor/applaunch/demo/service_test.go
- orchestrator/careplancontributor/applaunch/session/data.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
- orchestrator/careplancontributor/service.go
The `/cpc/ehr` proxies calls to the EHR's FHIR API, but it should try cached resources from session first (it contains resources that aren't available in the EHR's FHIR API). Recent refactor broke this.
> Fix enrolment due to broken cached FHIR resources in session

- orchestrator/messaging/azservicebus.go
At night, Azure seems to be having network issues on Service Bus now and then, leading to:
```go
created by github.com/SanteonNL/orca/orchestrator/messaging.(*AzureServiceBusBroker).receive in goroutine 1
/go/messaging/azservicebus.go:122 +0xb6
/go/messaging/azservicebus.go:141 +0x6d0
github.com/SanteonNL/orca/orchestrator/messaging.(*AzureServiceBusBroker).receive.func1()
panic: runtime error: index out of range [0] with length 0
```
> Fix Azure Service Bus out of bounds error

- deployments/dev/clinic/config/nginx-proxy.conf
- deployments/dev/docker-compose.yaml
- deployments/dev/hospital/config/nginx-proxy.conf
Applications were rebuilding (or at least for the one where I didn't forget to mount the source folder), but were not automatically refreshed due to NGINX missing config to proxy the Webpack HMR websocket.
Now, Demo EHR, Demo Viewer and Frontend properly hot reload.
> DEV-319: Fix hot reloading for NextJS applications

- hospital_simulator/app/(DashboardLayout)/components/patients/patient-overview.tsx
- hospital_simulator/app/(DashboardLayout)/components/patients/patient-table.tsx
Currently, new patients are added at the bottom of the table, which is annoying. This reverses that sort order (date/time created). Or actually fix it (because it was intended to work like that, but broken).
> Hospital simulator: sort patient overview descending order 

- orchestrator/careplancontributor/applaunch/smartonfhir/service.go
So we don't leak security info, and we can find the errors in the log
> SMART on FHIR: log launch errors, show generic error to the user

- orchestrator/careplancontributor/oidc/op/service_test.go
- orchestrator/careplancontributor/oidc/op/storage.go
Since they contain no sensible values, and they're optional in OIDC.
> DEV-506: Remove ACR and AMR OIDC id_token claims

- orchestrator/careplancontributor/applaunch/zorgplatform/README.md
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_create_access_token_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_validation.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_validation_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_integration_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
This allows for:
- Key rotation by ChipSoft
- Impersonating Zorgplatform for debugging purposes (if configured)
> DEV-606: Allow configuration of multiple Zorgplatform signing certs

- orchestrator/careplancontributor/applaunch/zorgplatform/handle_create_access_token_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_validation.go
- orchestrator/careplancontributor/applaunch/zorgplatform/handle_validation_test.go
- orchestrator/careplancontributor/applaunch/zorgplatform/saml_hix_sso_assertion.xml
- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
Also changes practitioner identifiers from 2 separate identifiers to 1 compound identifier. They were 2 identifiers, 1 for the org, 1 for the practitioner, but this is wrong: a single identifier should identify the resource, so it can't be spread over 2 identifiers.
I checked the usage, the identifier isn't used outside of ORCA, so no impact on other systems.
> DEV-610: Fix OIDC launch bug "no identifier in practitioner resource" because Zorgplatform app launch takes generalPractitioner as current user

- orchestrator/careplancontributor/applaunch/zorgplatform/service.go
- orchestrator/careplancontributor/batch.go
- orchestrator/careplancontributor/ehr/notification_bundle.go
- orchestrator/careplancontributor/ehr/notifier.go
- orchestrator/careplancontributor/handle_taskfiller.go
- orchestrator/careplancontributor/handle_taskfiller_test.go
- orchestrator/careplancontributor/integration_test.go
- orchestrator/careplancontributor/service.go
- orchestrator/careplancontributor/taskengine/workflow.go
- orchestrator/careplanservice/handle_createtask.go
- orchestrator/careplanservice/handle_updatetask.go
- orchestrator/careplanservice/integration_test.go
- orchestrator/careplanservice/operation_create.go
- orchestrator/careplanservice/operation_read.go
- orchestrator/careplanservice/operation_search.go
- orchestrator/careplanservice/operation_update.go
- orchestrator/careplanservice/service.go
- orchestrator/careplanservice/subscriptions/manager.go
- orchestrator/cmd/server_test.go
- orchestrator/lib/coolfhir/azure.go
- orchestrator/lib/coolfhir/azure_test.go
- orchestrator/lib/coolfhir/traced_fhir_client.go
- orchestrator/lib/coolfhir/traced_http_transport.go
- orchestrator/lib/otel/config.go
- orchestrator/lib/otel/config_test.go
Change import alias to use `otel` for our own internal package, and `baseotel` for the official package, since we use that import far less
> [DEV] Refactor otel_lib package usage
