SanteonNL/orca

orchestrator/careplancontributor/assets/completed.html
orchestrator/careplancontributor/assets/index.html
orchestrator/careplancontributor/service_integration.go

It's not pretty code, but OK for now.

Styling for Onboarding app

---

orchestrator/careplancontributor/service_test.go
orchestrator/lib/coolfhir/proxy.go
orchestrator/lib/coolfhir/proxy_test.go

And added some sanitizing, and unit tests.

Fix FHIR proxy not forwarding URL query parameters

---

orchestrator/careplanservice/service.go
orchestrator/careplanservice/service_test.go
orchestrator/careplanservice/util.go
orchestrator/lib/coolfhir/constants.go

[INT-255: Return OperationOutcome on error](https://linear.app/zorg-bij-jou/issue/INT-255/orca-or-return-operationoutcome-on-error-and-parse-them-client-side)

Return OperationOutcome instead of plain-text Error

---

orchestrator/cmd/nuts/csd.go
orchestrator/cmd/nuts/csd_test.go
orchestrator/go.mod
orchestrator/go.sum
orchestrator/lib/csd/interface.go
orchestrator/lib/csd/package.go

Implemented using Nuts Discovery Service.
Not actually used yet, but required for INT-214.

INT-200: Lookup endpoints through CSD (CareServiceDiscovery) Directory

---

hospital_simulator/utils/config.ts

Extracting the created `Practitioner` in the url creation now. In the future, it needs a rework there the `ServiceRequest.requester` point to a `PractitionerRole`.

INT-282: Added a tmp hotfix to retrieve the practitioner id in enrollment url creation.

---

orchestrator/careplanservice/service.go
orchestrator/careplanservice/service_test.go

The handler was just returning the transaction Bundle's response, but it also needs to read the actual created resource from the FHIR API, since the tx Bundle does not include created resource itself. This caused `null` to be returned to the client.

INT-361: Fix FHIR response of unmanaged create/update operations

---

e2e-tests/orca.go
orchestrator/README.md
orchestrator/cmd/config.go
orchestrator/cmd/profile/nuts/config.go
orchestrator/cmd/profile/nuts/config_test.go
orchestrator/cmd/profile/nuts/csd.go

Was hardcoded for some reason.

Make Nuts Discovery Service ID configurable

---

deployments/dev/hospital/docker-compose.yaml

Is the default, but better to be explicit?

Dev: set ORCA_PERFORMER_ORGANIZATION_URA

---

orchestrator/careplanservice/service.go
orchestrator/careplanservice/service_test.go

And set `total` while we're at it.

INT-393: Set Bundle.type to transaction-response for CPS bundles

---

orchestrator/careplancontributor/service.go
orchestrator/careplanservice/service.go
orchestrator/careplanservice/service_test.go
orchestrator/careplanservice/util.go
orchestrator/lib/coolfhir/bundle.go
orchestrator/lib/coolfhir/bundle_test.go
orchestrator/lib/coolfhir/constants.go
orchestrator/lib/coolfhir/error.go
orchestrator/lib/coolfhir/proxy.go
orchestrator/lib/coolfhir/util.go

Also removed some unused code.

INT-395: Set right content-type for bundle responses, deduplicate response marshalling

---

deployments/dev/start.sh
orchestrator/careplancontributor/handle_taskfiller.go
orchestrator/careplancontributor/handle_taskfiller_test.go
orchestrator/careplancontributor/service.go

Add task update to the task filler to allow for subtasks to be completed and the flow to continue

[INT-383] Fix dev test environment

---

orchestrator/careplanservice/handle_createtask.go
orchestrator/careplanservice/handle_createtask_test.go
orchestrator/lib/coolfhir/util.go
orchestrator/lib/coolfhir/util_test.go
orchestrator/lib/deep/util.go
orchestrator/lib/deep/util_test.go

INT-418: Support identifying patient through local reference

---

deployments/.gitignore
deployments/README.md
deployments/dev/hospital/docker-compose.yaml

Also enabled `ORCA_CAREPLANSERVICE_ALLOWUNMANAGEDFHIROPERATIONS` as the CPC forwards the `ServiceRequest` to the CPS.

Made Zorgplatform work on the dev deployment. Disabled by default. 

---

frontend/app/enrollment/components/enrollment-details-view.tsx
frontend/lib/store/enrollment-store.ts
hospital_simulator/app/(DashboardLayout)/components/service-requests/create-service-request-dialog.tsx
orchestrator/careplancontributor/applaunch/zorgplatform/service.go
viewer_simulator/app/(DashboardLayout)/components/onboarding/accepted-task-overview.tsx

Also added Zorgplatform "magic" fetch the Condition based on this reasonReference, which can be cached. The "fractuur van pols" has been replaced with "Hartfalen" for demo purposes.

Added logic to pre-select a Condition by setting the ServiceRequest.reasonReference

---

orchestrator/cmd/profile/nuts/csd.go
orchestrator/cmd/profile/nuts/csd_test.go
orchestrator/cmd/profile/nuts/profile.go

Should speedup the enrolment process a bit. 30 seconds cache should be enough to long enough for most interactions.

Orchestrator: cache CSD lookups

---

viewer_simulator/app/(DashboardLayout)/components/onboarding/accepted-task-overview.tsx

It turns out that the CPS no longer returned `Bundle.total`. Using the presence and length of `Bundle.entry` instead.

Bugfix in the viewer, it stopped displaying Tasks. 

---

e2e-tests/main_test.go
orchestrator/careplanservice/handle_getquestionnaireresponse.go
orchestrator/careplanservice/handle_getquestionnaireresponse_test.go
orchestrator/careplanservice/service.go

A user that has access to a Task also has access to any QuestionnaireResponse in its Output

[FIX] Implement task-output search param for QuestionnaireResponse auth

---

orchestrator/careplanservice/service.go

This is required for Azure FHIR server

[FIX] Re-index newly created custom search parameters

---

orchestrator/careplancontributor/config.go
orchestrator/cmd/config.go
orchestrator/cmd/config_test.go

Default config of CPC wasn't actually used.

Fix session timeout default

---

orchestrator/careplancontributor/handle_taskfiller.go
orchestrator/careplancontributor/handle_taskfiller_test.go
orchestrator/careplancontributor/service.go
orchestrator/careplancontributor/taskengine/workflow.go
orchestrator/careplanservice/integration_test.go
orchestrator/lib/slices/util.go
orchestrator/lib/slices/util_test.go

Introduces an interface for `WorkflowProvider`, which we can implement with a store fetching Questionnaires from a FHIR API.

INT-464: Prepare fetching Questionnaires from FHIR API

---

e2e-tests/main_test.go
orchestrator/careplancontributor/handle_taskfiller.go
orchestrator/careplancontributor/handle_taskfiller_test.go
orchestrator/careplancontributor/service.go
orchestrator/careplancontributor/service_test.go

Needs to implement the following state diagram: https://github.com/SanteonNL/shared-care-planning/blob/prestation-hl7-wgm/input/images-source/notification-task-flow.svg

INT-399: Reject Task if Task Filler engine can't execute it

---

frontend/app/enrollment/components/questionnaire-renderer.tsx
frontend/app/enrollment/layout.tsx
frontend/app/enrollment/new/page.tsx
frontend/app/enrollment/success/page.tsx
frontend/lib/store/enrollment-store.ts

- Contains feedback fixes from Juliet
- Fix weird reloading bug of the enrollment confirm screen

INT-502: enrollment UI improvements

---

orchestrator/careplancontributor/applaunch/zorgplatform/service.go
orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go

Also translates the service and condition codes to Dutch

INT-506: Improve hotfix for Zorgplatform activitydefinition mapping

---

orchestrator/careplancontributor/applaunch/zorgplatform/service.go
orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
orchestrator/careplancontributor/service.go
orchestrator/lib/coolfhir/proxy.go
orchestrator/lib/coolfhir/proxy_test.go

Prep work, still needs to be changed in Viewer Demo app. This just adds support.

INT-510: Rewrite POST-search to GET-search when proxying to Zorgplatform

---

orchestrator/careplancontributor/applaunch/zorgplatform/handle_create_access_token.go
orchestrator/careplancontributor/applaunch/zorgplatform/handle_create_access_token_test.go
orchestrator/careplancontributor/applaunch/zorgplatform/service.go
orchestrator/careplancontributor/applaunch/zorgplatform/service_integration_test.go
orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go

This supports unified logging and timeout management

INT-513 | Pass ctx through Zorgplatform

---

orchestrator/careplancontributor/ehr/notifier.go
orchestrator/careplancontributor/ehr/notifier_test.go

Refactored calls to the FHIR client to use SearchWithContext for better context handling and query parameter management. Updated associated tests to match the new method signature, ensuring consistent behavior across the application.

INT-492: EHR Notifier: Replace Read method with SearchWithContext in FHIR client

---

orchestrator/careplancontributor/applaunch/demo/service.go
orchestrator/careplancontributor/applaunch/smartonfhir/service.go
orchestrator/careplancontributor/applaunch/zorgplatform/handle_create_access_token.go
orchestrator/careplancontributor/applaunch/zorgplatform/service.go
orchestrator/careplancontributor/ehr/servicebus_client.go
orchestrator/careplancontributor/handle_taskfiller.go
orchestrator/careplancontributor/service.go
orchestrator/careplancontributor/taskengine/workflow.go
orchestrator/careplancontributor/taskengine/workflow_test.go
orchestrator/careplanservice/service.go
orchestrator/careplanservice/service_test.go
orchestrator/user/session.go

INT-560: More occurrences of missing principal on log entries

---

frontend/app/enrollment/components/questionnaire-renderer.tsx
frontend/app/enrollment/layout.tsx
frontend/app/enrollment/new/components/enrollment-details.tsx
frontend/app/enrollment/new/page.tsx
frontend/app/enrollment/task/[taskId]/page.tsx
frontend/app/layout.tsx
frontend/lib/store/task-progress-store.ts

Processed Juliet's feedback from Figma. 
This PR also contains some additional improvements:
1. fixed a bug where the UI showed "Task is ontvangen, maar er ontbreekt informatie" and "Taak niet gevonden"
2. The breadcrumb in the `isLastStep == true` state is remove, but is now set to `visibility: hidden`. This way, the header keeps its original height as per Figma design

Enrolment process UI improvements

---

viewer_simulator/app/(DashboardLayout)/components/onboarding/accepted-task-overview.tsx

This was preventing the page from fetching bundles and displaying tasks

Remove pre-rendering from accepted-task-overview.tsx

---

orchestrator/careplanservice/handle_createtask.go
orchestrator/careplanservice/handle_createtask_test.go
orchestrator/careplanservice/integration_test.go
orchestrator/careplanservice/service.go
orchestrator/careplanservice/subscriptions/manager.go
orchestrator/careplanservice/subscriptions/manager_test.go

Send notifications for careplans, currently only to the participants of the connected careteams.

INT-590 | Send careplan notifications

---

orchestrator/careplancontributor/ehr/notification_bundle.go
orchestrator/careplancontributor/ehr/notification_bundle_test.go
orchestrator/careplancontributor/ehr/notifier_test.go
orchestrator/lib/test/fhirclient.go

There is an issue with the reference to a patient resource that will be fixed in another PR, for now we can get the correct patient reference from the CarePlan
Found some issues with the validation logic so this has been fixed as well

INT-623 | Get Patient from CarePlan for notification

---

hospital_simulator/app/(DashboardLayout)/components/service-requests/create-service-request-dialog.tsx

For easier integration downstream;
- Remove "MiddleName" const string from patient name (incorrect)
- Generate random email address

INT-617: Fix testdata generation in hospital simulator

---

orchestrator/careplanservice/service.go
orchestrator/careplanservice/service_test.go
smartonfhir_backend_adapter/go.mod

Ensure content type for Search is `application/x-www-form-urlencoded`

INT-647 | CarePlanService FHIR search must verify HTTP request

---

orchestrator/README.md
orchestrator/messaging/http.go
orchestrator/messaging/http_test.go

We'll be having more topics soon, so we need to be able to filter.

INT-611: Allow filtering of topics enabled for sending to HTTP endpoint

---

orchestrator/careplancontributor/service.go
orchestrator/careplancontributor/service_test.go

Return empty string for unset context elements

Fix nil pointer #2 after session refactor 

---

orchestrator/careplancontributor/oidc/service.go
orchestrator/careplancontributor/oidc/storage.go

DEV-108: Logging, cleanup

---

frontend/app/enrollment/new/components/enrollment-details.tsx
frontend/app/enrollment/task/[taskId]/page.tsx
frontend/app/globals.css

Make it align more with what's designed (the description and "Test App" button title depend on the configuration of the environment);

DEV-357: Update styling

---

deployments/dev/README.md
deployments/dev/docker-compose.yaml

Port conflict with another system meant we needed to change this port

Updated the port of the clinic proxy

---

orchestrator/careplancontributor/applaunch/zorgplatform/service.go
orchestrator/careplancontributor/applaunch/zorgplatform/service_test.go
orchestrator/careplancontributor/batch.go
orchestrator/careplancontributor/batch_test.go
orchestrator/careplancontributor/integration_test.go
orchestrator/careplancontributor/service.go
orchestrator/careplancontributor/service_test.go
orchestrator/careplanservice/operation_read_test.go
orchestrator/cmd/server.go
orchestrator/lib/coolfhir/bundle.go
orchestrator/lib/coolfhir/proxy.go
orchestrator/lib/test/fhirclient.go

Logic-wise, it's now partially duplicate with the CPS transaction handling; could/should be refactored at some point, but probably fine for now.

DEV-725: Support FHIR bundle of type batch for querying EHR FHIR API

---

orchestrator/careplanservice/service_test.go
orchestrator/careplanservice/validate_patient.go
orchestrator/careplanservice/validate_patient_test.go

Updated the dutch phone number validator to be more robust

Fixed the dutch phone number validator

---

README.md
frontend/app/enrollment/components/sse-connection-status.tsx
frontend/app/enrollment/task/[taskId]/page.tsx
frontend/lib/store/task-progress-store.ts
orchestrator/careplancontributor/service.go
orchestrator/careplancontributor/service_test.go
orchestrator/careplancontributor/sse/service.go
orchestrator/careplancontributor/sse/service_test.go

This reverts commit 0fcf0d98bf6ce2a0237973168d725eed50d98bb4.
It breaks the task flow in ORCA Frontend.

Revert "Remove Server-Sent-Eventing for updating ORCA Frontend (#733)"

---

orchestrator/cmd/tenants/tenant.go
orchestrator/cmd/tenants/tenant_test.go

If it contains characters not allowed in URL paths, things will get ugly.

DEV-588: Validate tenant ID

---

orchestrator/cmd/server.go
orchestrator/go.mod
orchestrator/go.sum

Works locally but not in azure container, reverting now until I can diagnose the issue

[FIX] Revert OTEL log export

---

orchestrator/careplancontributor/applaunch/demo/service_test.go
orchestrator/go.mod
orchestrator/go.sum

Check is implemented in go-fhir-client

DEV-889: Prevent path traversal of FHIR requests
